### ISSUE TITLE
Add deploy to Vercel documentation

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack.github.io#110]
Add deploy to Vercel documentation

**Comment by franciscocandido** [comment]
I can do this

**Comment by Mortaro** [comment]
Awesome ⭐

Thanks! this is a little bit harder than the others because its not documented yet. 

However we have an working example in here using an also undocumented feature called 'Serverless Runners'

https://github.com/Mortaro/nullstack-vercel-example

Notice the way the app is exported in index.js and imported inside api/nullstack.js

Also the vercel.json configs

**Comment by franciscocandido** [comment]
Create a category called "Deployment" or a link within the "How to Deploy" page with Vercel documentation?

**Comment by Mortaro** [comment]
I think adding a Deploy category before examples might be the best option as the list of hosts will grow.

We could have links for node hosts in general + static deploy, heroku and vercel for now

**Comment by GuiDevloper** [comment]
Hey, @franciscocandido!

First, thanks for your will to contribute!

I'll be looking forward for solving those this week and better to ask before, have you done some work on this? :)

**Comment by franciscocandido** [comment]
@GuiDevloper 

When I got this problem I was still without classes. A few more days later they returned and I haven't had time for anything since. Not even to study.

You can continue this without me, I don't know when I'm going to have free time for now.

**Comment by Mortaro** [comment]
@franciscocandido i feel that! life is currently stomping me when time is the matter. Good luck <3

(if anyone else is reading this, i am using my free time to build Nullstack native yaay)
