### ISSUE TITLE
Translate docs for build modes

### ISSUE THREAD

**Issue by Mortaro** [nullstack/nullstack.github.io#137]
The changes for English version can be found at https://github.com/nullstack/nullstack.github.io/pull/136

Precisamos de ajuda para traduzir para Português <3

**Comment by hmartiins** [comment]
Hey, I saw this issue and was interested in contributing to it, but I wasn't sure what specifically should be translated and I also couldn't find which file or folder should be translated, could you help me with that?

**Comment by Mortaro** [comment]
Heyo, thanks for the interest <3

The files are in the branch "build-modes"  you can check the PR #136 for a diff, basically its every file in that diff outside of the docs folder

**Comment by Mortaro** [comment]
Oops forgot to close this one, thanks again @hmartiins
