### ISSUE TITLE
Bug - layout break

### ISSUE THREAD

**Issue by eugenio-silva** [nullstack/nullstack.github.io#174]
Description: Displays layout break at two breakpoints (768 and 1024) in some topics.

Evidence images:

![Screenshot from 2022-02-06 17-48-39](https://user-images.githubusercontent.com/61623623/152701010-580bbbbc-066d-4cc6-bfd1-9478d78baab9.png)

![Screenshot from 2022-02-06 17-49-07](https://user-images.githubusercontent.com/61623623/152701021-fe42b628-90b2-447c-9819-5e2dcfc495c1.png)

**Comment by GuiDevloper** [comment]
Welcome, @eugenio-silva!

Thanks for pointing it out!
I was able to reproduce it here and will send a fix fast as possible.

**Comment by Mortaro** [comment]
Thanks you both (o゜▽゜)o☆
