### ISSUE TITLE
Add docs about Custom Webpack Configuration

### ISSUE THREAD

**Issue by GuiDevloper** [nullstack/nullstack.github.io#182]
With [this upgrade](https://github.com/nullstack/nullstack/pull/191) the Webpack internal config of Nullstack will be locally configurable.
And Purge no more will be ran by default in production.
We definitely need docs for that!

- It should (re)move the Purge part from [styles doc](https://nullstack.app/styles) and use as example.
- It should bring examples of real config (e.g. examples repo with plugins/loaders).
- The future [NJS/NTS docs](https://nullstack.app/njs-file-extension) could link to here when "alternatively use extension like `.tsx`".

**Comment by Mortaro** [comment]
English documentation added, missing portuguese docs and also clean up on styles docs
