### ISSUE TITLE
Add night mode to documentation

### ISSUE THREAD

**Issue by GuiDevloper** [nullstack/nullstack.github.io#42]
I ended working on translations at night, which motivated me to experiment how an night mode would look by simple inverting colors:

<img src="https://user-images.githubusercontent.com/31557312/107462083-13d60380-6b3a-11eb-90b4-4fa5d249d5f7.jpg" width="70%">

Along with an sweet-looking possibility of layout, looks like an opportunity to show how Nullstack behaves on the common use case that is re-styling whole views by user request.

What you guys think? The coloring is totally open to suggestions :)

**Comment by Mortaro** [comment]
Muito bom!

Esse projeto está usando "nullsheet" que é uma biblioteca de macros CSS (estilo tailwind mas com pegada de vim) que eu acabei nunca publicando, porém ela usa variaveis de CSS para definir cores em runtime. Para criar um night mode global bastaria usar javascript para setar a variavel com a nova com no css. 

Se quiser arriscar a implementação o @daysonmarx  pode revisar as cores depois!
