### ISSUE TITLE
Adaptar Contributors para i18n e traduzir

### ISSUE THREAD

**Issue by GuiDevloper** [nullstack/nullstack.github.io#44]
Dei uma olhada em qual seria a tradução seguinte e seguindo as principais é a Contributors que vi não ter yml e nem estava adaptada para tal.
Não sei o que me deu que resolvi aprender e realizar essa adaptação :sweat_smile:

Mandarei PR disso e caso eu tenha me equivocado ou perdido algo, pode corrigir!

**Comment by Mortaro** [comment]
Respondi no PR mas novamente: Muito obrigado! 💖

**Comment by Mortaro** [comment]
Refatorei de leve o código no commit: 4b699ddeeef3d43d6cbfb0cb1341342046d36acd

A tua versão com anchor na minha opinião é mais elegante, mas eu acabei voltando para uma tag <a> para pessoas que verem o código por motivos de aprendizado não se confumdam e pensem que precisa de algum plugin como react-router para lidar com ancoras

**Comment by GuiDevloper** [comment]
Hey @Mortaro, vamos voltar nessa que achei alguns problemas com as urls dos Contributors.

Acho que meu Archor realmente complicou a interpretação do código, dando uma ludibriada até no criador do framework :sweat_smile: 

Desculpa qualquer coisa, já mando a PR com hotfix necessário.
