### ISSUE TITLE
Problema na renderização de componente de código na landing page

### ISSUE THREAD

**Issue by GPoleto27** [nullstack/nullstack.github.io#49]
# Informações do Sistema:
- OS: Manjaro Linux x86_64
- Kernel: 5.9.16-1-MANJARO
- Resolução (total, 2 monitores): 3520x1080
    - Resolução (principal): 1920x1080
    - Resolução (secundário): 1600x900
- Desktop Environment: Plasma 5.20.5
- Window Manager: KWin
- Browser: Mozilla Firefox for Manjaro Linux Version 85.0.1 (64-bit)

Edit: alterei a imagem pra ficar mais visível o problema (antes a navbar estava no meio da tela, mas, por causa do print, não um erro de renderização)
![image](https://user-images.githubusercontent.com/25328537/107588071-bb5a4100-6be1-11eb-9cde-6cf86d163df2.png)

**Comment by Mortaro** [comment]
Segue imagem no Edge para windows por referência de como deveria estar:

![download](https://user-images.githubusercontent.com/4305930/107591515-979af900-6be9-11eb-8903-33811f402170.png)

**Comment by daysonmarx** [comment]
O problema existe no Chrome no Ubuntu 20.04 também!

![2021-02-10-21-54-nullstack app](https://user-images.githubusercontent.com/46573947/107592065-bea5fa80-6bea-11eb-89d4-32c47ef9f226.png)

**Comment by Mortaro** [comment]
![ff](https://user-images.githubusercontent.com/4305930/107595736-4ba18180-6bf4-11eb-9ec1-de157d8c2641.png)

Tornei mais largas as sessões com código e reduzi 0.1rem a fonte especificamente no Firefox, creio que a legibilidade tenha melhorado.

A alternativa seria alterar o código mas eu tava tao faceiro que todos os exemplos tem exatamente o mesmo número de linhas 💜

Farei o deploy quando as traduções avançarem mais um pouco.
