### ISSUE TITLE
Snippets are overflowing

### ISSUE THREAD

**Issue by fariasmateuss** [nullstack/nullstack.github.io#64]
Hey, 

First: Awesome project!

Up front... Snippets are overflowing, as in the image below.

![image](https://user-images.githubusercontent.com/55674918/109089387-88d33c80-76e7-11eb-9edb-88851d6c01aa.png)

**Comment by Mortaro** [comment]
Thanks for the warning!

This has been fixed in #49  but we did not deploy it yet :(

Soon @GuiDevloper will deploy it along the new home with dark mode (～￣▽￣)～

**Comment by Mortaro** [comment]
The preview is online, pressuring @GuiDevloper  worked! ill close this issue if something new happens please let me know!
